#!/usr/bin/env node

const fs = require('fs')
const path = require('path')
const program = require('commander')

program
  .version('1.0.0')

fs
  .readdirSync(path.join(__dirname, './commands'))
  .filter(file => file.indexOf('.') !== 0 && (file.slice(-3)) === '.js')
  .forEach(file => {
    const command = require(path.join(__dirname, './commands', file))
    command(program)
  })

program.parse(process.argv)
